services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sto'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'
